id: PEAE1BEB5
initial_creation_type: input
source_metadata:
  title: Adzom Drukpa Series
  language: bo
  description: 'Texts by and about Adzom Drukpa Drodül Pawo Dorje (a ''dzoms ''brug
    pa ''gro ''dul dpa'' bo rdo rje, 1842–1924):'
  volume:
    ace3b1f7785d4effbe4b4c498b0b217f:
      title: 'The Hook of Blessing and Compassion: An Invocation Recalling Briefly
        the Life and Liberation of the Drukchen Drodül Pawo Dorje, My Loving Supreme
        Guru'
      parent: Biography
    cfb5cb7a4847462f8aaaaf5db14f4066:
      title: 'The Ambrosia of Blessings: A Prayer to the Vidyādhara of Unparalleled
        Kindness, Drodül Pawo Dorje'
      parent: Prayers
created_at: '2022-02-28T22:34:53.368206'
last_modified_at: '2022-02-28T22:34:53.368208'
statistics:
  total_words: 2229
  total_non_words: 143
quality:
  non_words_ratio: 0.06
